database:
  mysql:
    connect: false
    host: "127.0.0.1"
    port: 3306
    username: "root"
    password: "12345"
    host-database: coinapi,data
  mongodb:
    connect: false
    host: "127.0.0.1"
    port: 27017
    host-database: coinapi,data